apiVersion: v1
kind: Secret
metadata:
  name: tls
  namespace: portfolio
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
  # tls.crt: {{ .Files.Get "secrets/tls.crt" | b64enc }}
  # tls.key: {{ .Files.Get "secrets/tls.key" | b64enc }}
