apiVersion: v1
kind: Service
metadata:
  name: infrastructure-overview
  namespace: portfolio
spec:
  selector:
    app: infrastructure-overview
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
