kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: portfolio
spec:
  type: ExternalName
  externalName: grafana.metrics.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
