apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: portfolio
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.db.name }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.db.root_password }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
        - image: busybox:latest
          name: busybox
          command: ['sh', '-c', 'while true; do echo "hey"; sleep 3; done']
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
              readOnly: true
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
