kind: Service
apiVersion: v1
metadata:
  name: jenkins-expose-service
  namespace: portfolio
spec:
  type: ExternalName
  externalName: jenkins.jenkins.svc.cluster.local
  ports:
    - port: 80
      targetPort: 8080
