name: Deploy
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    name: Deploy infrastructure & cluster
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Create Terraform crdentials file
        run: 'mkdir ~/.terraform.d && echo "{ \"credentials\": { \"app.terraform.io\": { \"token\": \"${TF_CLOUD_TOKEN}\" } } }" > ~/.terraform.d/credentials.tfrc.json'
        env:
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
      - name: Init Cloud
        run: terraform -chdir="cloud" init
      - name: Plan Cloud
        env:
          TF_VAR_token: ${{ secrets.TF_VAR_token }}
        run: terraform -chdir="cloud" plan -var-file="terraform.tfvars"
      - name: Apply Cloud
        env:
          TF_VAR_token: ${{ secrets.TF_VAR_token }}
        run: terraform -chdir="cloud" apply -auto-approve
      - name: Init Cluster
        run: terraform -chdir="cluster" init
      - name: Download Kubeconfig
        run: terraform -chdir="cloud" output -raw kubeconfig | base64 -d > ./cluster/secrets/kubeconfig
      - name: Plan Cluster
        run: terraform -chdir="cluster" plan -var-file="variables.secret.tfvars"
      - name: Apply Cluster
        run: terraform -chdir="cluster" apply -var-file="variables.secret.tfvars" -auto-approve
