name: Deploy
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    container:
      image: hashicorp/terraform:1.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact