name: Deploy
on:
  push:
    branches:
      - "main"
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: state-artifact
          path: |
            ./
            !.git
  terraform-login:
    name: Terraform Login
    needs: checkout
    runs-on: ubuntu-22.04
    env:
      TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
    steps:
      - name: Create Terraform crdentials file
        run: 'mkdir ~/.terraform.d && echo 
          {
            "credentials": { 
              "app.terraform.io": { 
                "token": "$TF_CLOUD_TOKEN" 
              } 
            } 
          } > ~/.terraform.d/credentials.tfrc.json'
      - name: Upload Terraform credentials
        uses: actions/upload-artifact@v3
        with:
          name: terraform-credentials-artifact
          path: ~/.terraform.d
  terraform-cloud:
    name: Terraform Cloud
    needs: terraform-login
    runs-on: ubuntu-22.04
    container:
      image: hashicorp/terraform:1.5
    steps:
      # - name: Download artifacts
      - uses: actions/download-artifact@v3
        with:
          name: state-artifact
          path: ./
      - uses: actions/download-artifact@v3
        with:
          name: terraform-credentials-artifact
          path: ~/.terraform.d
      - name: Test
        run: cat ~/.terraform.d/credentials.tfrc.json
      - name: Init
        run: terraform -chdir="cloud" init
      - name: Plan
        env:
          TF_VAR_token: ${{ secrets.TF_VAR_token }}
        run: terraform -chdir="cloud" plan -var-file="terraform.tfvars" -out plan
      - name: Apply
        env:
          TF_VAR_token: ${{ secrets.TF_VAR_token }}
        run: terraform -chdir="cloud" apply plan
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: state-artifact
          path: ./
  terraform-cluster:
    name: Terraform Cluster
    needs: terraform-cloud
    runs-on: ubuntu-22.04
    container:
      image: hashicorp/terraform:1.5
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: state-artifact
          path: ./
      - name: Init
        run: terraform -chdir="cluster" init
      - name: Plan
        run: terraform -chdir="cluster" plan -var-file="variables.secret.tfvars" -out plan
      - name: Apply
        run: terraform -chdir="cluster" apply plan
  clean-up:
    needs: terraform-cluster
    name: Clean Up
    runs-on: ubuntu-22.04
    container:
      image: hashicorp/terraform:1.5
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: state-artifact